version: "3"
services:
  # consumer:
  #   image: jms-consumer
  # producer:
  #   image: jms-producer
  provider:
    image: vromero/activemq-artemis
    volumes:
      - activemq-artemis-data:/var/lib/artemis/data
      - activemq-artemis-etc:/var/lib/artemis/etc
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "8161:8161"
      - "61616:61616"
volumes:
  activemq-artemis-data:
  activemq-artemis-etc: