version: "3"
services:
  # consumer:

  # producer:

  provider:
    image: rmohr/activemq
    volumes:
      - activemq-data:/opt/activemq/data
      - activemq-conf:/opt/activemq/conf
    ports:
      - "61616:61616"

volumes:
  activemq-data:
  activemq-conf: